### ISSUE TITLE
你好，大佬还更新吗？4300v1用你编译的版本很好用

### ISSUE THREAD

**Issue by hwd1118** [jyy5206/OpenWRT-firmware-R20.1.24-for-Netgear-4300V1#1]
RT，谢谢大佬，3月大雕的源码更新了不少东西，4300v1还更新不？

**Comment by jyy5206** [comment]
好用就好
追新=自找麻烦
软件都是老的稳定
半年后再看吧
如果你喜欢折腾
可以自己尝试编译


hwd1118 <notifications@github.com> 于 2020年3月10日周二 21:11写道：

**Comment by hwd1118** [comment]
好的，还是谢谢你
